run:
  timeout: 3m

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - errorlint
    - gofmt
    - goimports
    - misspell
    - revive

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
